### ISSUE TITLE
JAXB unmarshalling error

### ISSUE THREAD

**Issue by singicus** [emoran/QuickBooksDesktopService#2]
Is there anything I should be doing to not receive this error:

(QBXML) jaxbUnmarshaller.unmarshal(new StringReader(receiveResponseXML.getResponse())) = >Exception occurred in target VM: unexpected element (uri:"", local:"QBXML"). Expected elements are (none)

This error occurs in the skeleton class.  Your example project has:
    	JAXBContext jaxbContext = JAXBContext.newInstance(QBXML.class);
        Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();    	
        **QBXML mainDocument = (QBXML) jaxbUnmarshaller.unmarshal(new StringReader(receiveResponseXML.getResponse()));**    		
            	
The error I get is:  (QBXML) jaxbUnmarshaller.unmarshal(new StringReader(receiveResponseXML.getResponse())) = >Exception occurred in target VM: unexpected element (uri:"", local:"QBXML"). Expected elements are (none)

Here's the XML request followed by XML response:
```
 java.net.URL url = QBWebConnectorSvcSkeleton.class.getResource("queryRq.xml");
this is queryRq.xml:
<?xml version="1.0" ?>
<?qbxml version="10.0" ?>
 <QBXML>
    <QBXMLMsgsRq onError = "stopOnError">
        <InvoiceQueryRq requestID ="0">
            <MaxReturned>1</MaxReturned>
            <IncludeRetElement >TxnID</IncludeRetElement>
        </InvoiceQueryRq>
    </QBXMLMsgsRq>
</QBXML> 



public ReceiveResponseXMLResponse receiveResponseXML(ReceiveResponseXML receiveResponseXML)
receiveResponseXML is:
<?xml version="1.0" ?>
<QBXML>
<QBXMLMsgsRs>
<InvoiceQueryRs requestID="0" statusCode="0" statusSeverity="Info" statusMessage="Status OK">
<InvoiceRet>
<TxnID>7-808571530</TxnID>
</InvoiceRet>
</InvoiceQueryRs>
</QBXMLMsgsRs>
</QBXML> ```

**Comment by singicus** [comment]
FOUND IT!  I am not sure it there is another way but this works:
Annotate QBXML.java class with

@XmlRootElement(name = "QBXML")

You'll need to add this import:
 import javax.xml.bind.annotation.XmlRootElement;


so that your class looks like this (provided a screen shot as well):
 import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "QBXML")
public class QBXML {	
	public QBXMLMsgsRs QBXMLMsgsRs;
}

![image](https://user-images.githubusercontent.com/2279558/99321792-a406f400-283c-11eb-82f4-b6be3f27ff51.png)

**Comment by emoran** [comment]
Thanks @singicus, are you deploying this to tomcat or it's a direct run from the code? I have seen that error before too when the Quickbooks Desktop client runs sometimes, so definitely this will be updated.

Best :)

**Comment by singicus** [comment]
I deployed to Tomcat, ran “Update Selected” from the QBWebConnector, and was debugging in NetBeans using the attached debugger (NetBeans deployment).
